### ISSUE TITLE
Track alert email opens with Matomo

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#116]
### Background
As the Bron developers, we want to know how often the alert emails are opened, so we learn how the Bron product is used.

### Proposed method
* Set up tags, triggers, and variables in the Bron Matomo Analytics instance.
* Email alert URLs are appended with a GET variable `UserID` (e.g. https://bron.live/h23lpqnB?UserID=901922)

### Resources
https://matomo.org/faq/how-to/faq_25454/

**Comment by breyten** [comment]
Fixed in https://github.com/openstate/binoas/commit/c437eb6740590b8cdbcbbb1fea405e77ffefdd77
