### ISSUE TITLE
Hamburger menu empty and visible on desktop

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#126]
## Describe the bug
**Summary**
The hamburger menu is empty and currently visible on desktop screens.

**URL / Environment**
https://bron.live

## Steps to reproduce**
1. Go to the Bron frontpage with a desktop device
2. Click on hamburger menu
3. See it empty (except Privacy notice)

## Expected behavior
The hamburger menu is only visible on smaller devices. The main menu is only visible on larger devices. Both menus contain the same items.

## Screenshots
![Image](https://github.com/openstate/jodal/assets/8989205/f0ff0b8a-9e06-4a1e-a9ac-7c0550fcc1a6)

## Additional context
None

**Comment by breyten** [comment]
Except it is not empty?

![image](https://github.com/openstate/jodal/assets/154791/6bb2ca24-6cc8-4df1-a5f9-9077c993f77a)
