### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#127]
## Describe the bug
**Summary**
The header styling differs a from the design in Figma in terms of elements displayed, font-sizes, and alignment of elements.

**URL / Environment**
https://bron.live

## Steps to reproduce**
1. View the [Figma design for the header](https://www.figma.com/file/Tcv7xuwikoVW0U8c0pqDDq/Graphics?type=design&node-id=303-85&mode=dev)
2. View the header on any page on bron.live
3. See the differences.

## Expected behavior
- Elements displayed are the same for design and implementation
- Alignment of logo and tagline elements are to the left
- Menu items are: Bronnen and Over ons (sources and about us) and are aligned to the right
- Font families and sizes are the same as specified in design
- Bottom border is implemented

## Additional context
Figma header design: https://www.figma.com/file/Tcv7xuwikoVW0U8c0pqDDq/Graphics?type=design&node-id=303-85&mode=dev

**Comment by breyten** [comment]
Leuk die figma maar ik heb dus geen idee welke van de drie designs ik in dat ding moet hebben

**Comment by vanderburgt** [comment]
The url under "Additional context" points directly to the components artboard in Figma. That artboard contains all the main components. The other artboards contain instances of those main components. For more info on components in Figma: https://help.figma.com/hc/en-us/articles/360038662654-Guide-to-components-in-Figma

**Comment by vanderburgt** [comment]
figma://www.figma.com/file/Tcv7xuwikoVW0U8c0pqDDq/Graphics?type=design&node-id=303-85&mode=dev

**Comment by vanderburgt** [comment]
* Border bottom: should be `#D9D9D9`
* `.logo-container` height property should be 42px. Now the bottom of the letter 'O' is cut off.
