### ISSUE TITLE
Jodal.nl still online

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#136]
Priority: High 🔴

## Describe the bug
**Summary**
Bron is pre-launch and in test mode but already publicly available at jodal.nl

**URL / Environment**
https://jodal.nl

## Steps to reproduce**
1. Go to jodal.nl
2. See Bron live

## Expected behavior
Jodal.nl redirects to bron.live, which is password protected

**Comment by breyten** [comment]
Fixed, still need to redirect the app.* domains but will do that on thursday.
