### ISSUE TITLE
Results list design

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#137]
## Describe the bug
**Summary**
Results list does not match design

**URL / Environment**
https://bron.live

## Steps to reproduce**
1. Go to bron.live
2. Scroll down to Preview resultate
4. See list with results that is different from design.

## Expected behavior
Results list matches design.

## Screenshots
Implemented
![Image](https://github.com/openstate/jodal/assets/8989205/3ce9dad1-7875-450c-940e-cb2d98ea5629)

Design
![Image](https://github.com/openstate/jodal/assets/8989205/ff9c8b3a-24be-4d7d-b771-851b44af42b7)

## Additional context
Suggested CSS changes:

.column-contents {
change:    line-height: 40px;

.entry {
remove:    border-bottom: 1px solid #ccc;
}

.column-contents {
change:    padding-top: 10px;
}

**Comment by breyten** [comment]
The lines between the items are there for a reason. Otherwise it becomes undistiguishable where an item starts and ends, especially once the subject will word wrap across multiple lines.
