### ISSUE TITLE
Bron.live search form not loading data

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#138]
## Describe the bug
**Summary**
The search form at bron.live is not loading data after entering search parameters.

**URL / Environment**
https://bron.live

## Steps to reproduce**
1. Go to bron.live
2. Enter any search keyword
3. Scroll down to the results list
4. See loading indicator seemingly stuck loading

## Expected behavior
Shows results according to entered search parameters

## Screenshots
![Image](https://github.com/openstate/jodal/assets/8989205/e2d82b20-4509-405b-bf5a-20e5a0ffe3d7)

**Comment by breyten** [comment]
Whoops, edited the wrong redirect. Fixed now

**Comment by vanderburgt** [comment]
Thx for the quick response!
