### ISSUE TITLE
Slow loading results (>60 secs)

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#140]
## Describe the bug
**Summary**
For some search queries, the results loading takes over 60 seconds.

**URL / Environment**
https://bron.live

## Steps to reproduce**
1. Go to 'bron.live
2. Enter search query: `windmolens`
3. Enter location: 'Groningen'
4. Scroll down to the results list
5. See results seemingly stuck loading, but showing results after a long time.

## Expected behavior
Shows the results within seconds.

**Comment by breyten** [comment]
Elasticsearch was given more memory, but that did not help ...

**Comment by breyten** [comment]
These changes make it performant. Now only the full text is left.
