### ISSUE TITLE
Auto-login with email link not registered

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#151]
## Describe the bug
**Summary**
When a user clicks a link in an alert email there is no login registered in FusionAuth

**URL / Environment**
Bron alert email and link to result via https://bron.live/{token}

## Steps to reproduce
1. Go to alert email
2. Click on a result link (https://bron.live/{token})
3. See redirect at bron.live to original source
4. Go to FusionAuth admin panel https://users.jodal.nl/admin/
5. Scroll to Recent Logins
6. See no new login registered for the user

## Expected behavior
The login is registered in FusionAuth

**Comment by breyten** [comment]
* Needs checking of the login cookie when the identity is being retrieved
* Also needs to trigger actual login once a user account is created (can be "passwordless")

**Comment by breyten** [comment]
Live and ready to test
