### ISSUE TITLE
Matomo not receiving analytics events

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#153]
## Describe the bug
**Summary**
Matomo is seemingly not receiving any events from Bron.live

**URL / Environment**
https://analytics.openstate.eu

## Steps to reproduce
1. Go to analytics.openstate.eu
2. Select the 'Jodal' site
3. View the analytics from the past days
4. See null visitors or actions

## Expected behavior
Events from user actions on Bron.live are sent to Matomo analytics and available for analysis in the 'Jodal' site dashboard.

## Screenshots
![Image](https://github.com/openstate/jodal/assets/8989205/b6ff74f7-9290-400e-ab90-b9b699d8b966)

## Additional context
- From personal use and activity recorded in FusionAuth we know that user events take place on Bron.live
- The Matomo tag seems to be correct on Bron.live

**Comment by vanderburgt** [comment]
A visitor history is now displayed, but new events don't seem to register. No visitors are recorded for today even though visits have occurred.

**Comment by breyten** [comment]
Fixed now (finally! ;))
