### ISSUE TITLE
Password reset email points to localhost

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#154]
## Describe the bug
**Summary**
The password reset email contains a link that points to http://localhost:9011/password/change...

**URL / Environment**
https://users.jodal.nl and user's email client

## Steps to reproduce
1. Go to users.jodal.nl
2. Click on 'Forgot your password?'
3. Enter existing user email address
4. Go to email inbox
5. See link in password reset email

## Expected behavior
Link in email leads to password reset form at users.jodal.nl

## Screenshots
![Image](https://github.com/openstate/jodal/assets/8989205/ff70cb5e-ab3a-423d-ad9e-82d64a01a5dd)

## Additional context
The password reset functionality is currently not exposed to users, so the issue is non-critical.

**Comment by breyten** [comment]
Fixed in Fusionauth template.
