### ISSUE TITLE
Spammy results from PoliFLW

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#158]
## Describe the bug
**Summary**
Some results from PoliFLW contain non-relevant, spammy, content

**URL / Environment**
https://bron.live/

## Steps to reproduce
1. Go to bron.live
2. Search for 'eemshaven google'
3. Scroll down to results
4. See results with titles such as: '10electronica.nl: Top 5 Robotstofzuigers'

## Expected behavior
Only relevant content is displayed.

## Screenshots
![Image](https://github.com/openstate/jodal/assets/8989205/fa90622c-21fc-4ec5-afc1-701439f476db)

## Additional context
* www.pvdavenlo.nl seems to be taken over by a spam group
* The Wordpress result seems to link directly to wordpress.com from PoliFLW (https://www.poliflw.nl/l/Almelo/Democraten%20NU/6c879cee355da2ad4acd280611ff40a9e95e3dfd)

**Comment by breyten** [comment]
Remove pvdavenlo and democraten nu
