### ISSUE TITLE
Web Archiver

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#169]
## User Story
As a Dutch journalist, I want a secure and straightforward way to archive webpages, so that I can ensuring the longevity and accessibility of my web sources, even after a web page has been taken offline.

## Acceptance Criteria
1. **Exclusive access for journalists:** *Given* that Bron aims to support journalistic work, *when* accessing the Web Archiver feature, *then* it should only be available to users who are logged in as registered journalists to prevent misuse of the service.

2. **Intuitive interface:** *Given* that I am using the Web Archiver tool, *when* I navigate to the Web Archiver page, *then* I should see clear instructions, an input field for web page URLs, an 'Archive' button for initiating downloads, and a list of previously archived web pages, enhancing the user experience and efficiency.

3. **Download archive:** *Given* that web pages I archived are available in my list, *when* I click on a 'downloaded' web page, *then* it should initiate a download of the web page in warc format, ensuring I have offline access when needed.

4. **Monitoring and resource management:** *Given* the need for sustainable operation, *when* the Web Archiver tool is used, *then* Bron should track usage statistics, compute, and storage costs associated with the feature to make informed decisions about resource allocation and potential future adjustments.

**Comment by breyten** [comment]
See [this page](https://docs.google.com/spreadsheets/d/1FqxwaZnIhhQ7jDCC-W64NMRf5rDeh2Shx3u01MsBmTQ/edit#gid=0) for a comparison of we archiving solutions

**Comment by breyten** [comment]
See [this](https://github.com/iipc/awesome-web-archiving?tab=readme-ov-file) for a list

**Comment by breyten** [comment]
Deployed
