### ISSUE TITLE
'Meer opties' hernoemen

### ISSUE THREAD

**Issue by siccovansas** [openstate/jodal#170]
'Meer opties' is onduidelijk, terwijl er op dit moment maar 1 soort optie onder valt, namelijk het selecteren van bronnen. Het zou duidelijker zijn om dit te hernoemen naar bv. 'Selecteer Bronnen'.

**Comment by vanderburgt** [comment]
Thanks for the suggestion and effort of writing an issue, Sicco! I'm moving this issue to https://github.com/openstate/jodal/issues/180 and closing this one.
