### ISSUE TITLE
Toon aantallen documenten/hits

### ISSUE THREAD

**Issue by siccovansas** [openstate/jodal#171]
Achter 'Preview resultaten' zou ik graag het totaal aantal hits zien, bv. 'Preview resultaten (1.652)'.

Achter het selecteren van Bronnen zou ik graag zien hoeveel hits er per bron zijn.

Op deze manier krijg ik een idee hoeveel data er beschikbaar is.

**Comment by vanderburgt** [comment]
Thanks for the suggestion and effort of writing an issue, Sicco! I'm moving this issue to https://github.com/openstate/jodal/discussions/179 and closing this one.
