### ISSUE TITLE
Allow for deep linking of queries

### ISSUE THREAD

**Issue by breyten** [openstate/jodal#173]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to forward a query on the bron website to someone else. This is currently not possible because the search query is always fixed

**Describe the solution you'd like**
Allow to get the query and/or other features via the url

**Describe alternatives you've considered**

**Additional context**

**Comment by breyten** [comment]
This allows for queries like `http://bron.live/?query=test`

**Comment by vanderburgt** [comment]
This is great! Will this also work for the selected additional settings (ie. sources and location)?
