### ISSUE TITLE
No recent results from Woogle

### ISSUE THREAD

**Issue by vanderburgt** [openstate/jodal#186]
## Describe the bug
**Summary**
When searching for recent Woo requests (FOI requests) no recent results turn up.

**URL / Environment**
https://bron.live

## Steps to reproduce
1. Replace 'windmolens' with *
2. Click on 'Meer opties'
3. Select only 'Woo verzoeken'
5. Scroll down to the results list
6. See only results until 21 February

## Expected behavior
The data comes from [Woogle](https://woogle.wooverheid.nl/search?page=1&country=nl) and on that site the most recent results are from 26 July. These results are expected to be included.

## Screenshots
![Image](https://github.com/user-attachments/assets/532416a6-e3c7-45e5-ba7b-6e1c6aab762d)

**Comment by breyten** [comment]
Url of overview page changed to https://pid.wooverheid.nl/?pid=nl
