### ISSUE TITLE
Open Spending via nieuwe OpenSpending API weer inladen?

### ISSUE THREAD

**Issue by siccovansas** [openstate/jodal#189]
**Is your feature request related to a problem? Please describe.**
De oude Open Spending API gaat eruit. Willen we de nieuwe nog in Bron laden of is deze data minder belangrijk?

**Comment by vanderburgt** [comment]
_Auto-translated original comment: "The old Open Spending API is going out. Do we still want to load the new one into Source or is this data less important?"_

Not a priority right now due to the static nature of Open Spending data.
